# Generated by Django 4.1.7 on 2023-02-21 15:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_image_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Текст комментария', max_length=5000, verbose_name='Текст'),
        ),
    ]
