# Generated by Django 4.1.7 on 2023-02-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время вносятся атоматически', verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время вносятся атоматически', verbose_name='Дата и время создания'),
        ),
    ]
