# Generated by Django 4.1.7 on 2023-02-23 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Назовите ресурс', max_length=50, null=True, verbose_name='Наименование ссылки')),
                ('link', models.URLField(help_text='URL-адрес ресурса', verbose_name='URL-адрес')),
                ('contact', models.ForeignKey(help_text='Контактное лицо', on_delete=django.db.models.deletion.CASCADE, to='about.about', verbose_name='Разработчик')),
            ],
        ),
    ]
