# Generated by Django 4.1.7 on 2023-02-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название технологии', max_length=200, verbose_name='Технология')),
                ('description', models.TextField(help_text='Описание Технологии', verbose_name='Описание')),
                ('number', models.IntegerField(db_index=True, help_text='Приоритет расстановки на странице', unique=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ('number',),
            },
        ),
    ]
