# Generated by Django 4.1.7 on 2023-02-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='is_studied',
            field=models.BooleanField(default=False, help_text='Уже изучено или ещё в планах', verbose_name='Изучено'),
        ),
    ]
