# Generated by Django 4.1.7 on 2023-02-23 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0002_tech_is_studied'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Описание Технологии', verbose_name='Описание')),
                ('photo', models.ImageField(help_text='Загрузите фото', upload_to='about/', verbose_name='Фотограия')),
                ('role', models.CharField(blank=True, help_text='Введите специальность', max_length=150, verbose_name='Специальность')),
                ('city', models.CharField(blank=True, help_text='Место проживания', max_length=50, verbose_name='Город')),
                ('user', models.ForeignKey(help_text='Автор сайта', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Разработчик')),
            ],
            options={
                'verbose_name': 'Разработчик',
                'verbose_name_plural': 'Разработчики',
            },
        ),
    ]
